// import type { Metadata } from "next";
"use client";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar/app-sidebar";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { store, persistor } from "./redux/store";
import { useEffect, useState } from "react";
import { detectDevice } from "@/utils/detectDevice";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [device, setDevice] = useState<string>('unknown');

  useEffect(() => {
    const userAgent = navigator.userAgent;
    const detectedDevice = detectDevice(userAgent); // Call the utility function
    setDevice(detectedDevice ?? 'unknown');
  }, []);


  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <html lang="en">
          <link rel="manifest" href="/manifest.json" />
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-auto`}
          >
            {" "}
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SidebarProvider>
                <AppSidebar />
                {/* <Navbar /> */}

                <main className="">
                  {device === "mobile" && 
                  <SidebarTrigger />
                }
                  {children}
                </main>
                {/* <Footer /> */}
              </SidebarProvider>
            </ThemeProvider>
          </body>
        </html>
      </PersistGate>
    </Provider>
  );
}
